name: Medium Blog Posts
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme
  
jobs:
  update-readme-with-Medium-Blog:
    name: Latest Posts From Medium
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name : "BLOG-POST-LIST"
          feed_list: "https://medium.com/@abhijeet00900"
